/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class DistinctElementsResult {
  
  @SerializedName("queryId")
  private String queryId = null;
  @SerializedName("distinctElements")
  private List<String> distinctElements = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getQueryId() {
    return queryId;
  }
  public void setQueryId(String queryId) {
    this.queryId = queryId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getDistinctElements() {
    return distinctElements;
  }
  public void setDistinctElements(List<String> distinctElements) {
    this.distinctElements = distinctElements;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DistinctElementsResult distinctElementsResult = (DistinctElementsResult) o;
    return (this.queryId == null ? distinctElementsResult.queryId == null : this.queryId.equals(distinctElementsResult.queryId)) &&
        (this.distinctElements == null ? distinctElementsResult.distinctElements == null : this.distinctElements.equals(distinctElementsResult.distinctElements));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.queryId == null ? 0: this.queryId.hashCode());
    result = 31 * result + (this.distinctElements == null ? 0: this.distinctElements.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DistinctElementsResult {\n");
    
    sb.append("  queryId: ").append(queryId).append("\n");
    sb.append("  distinctElements: ").append(distinctElements).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
