/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.MediaObjectDescriptor;
import org.openapitools.client.model.MediaObjectMetadataDescriptor;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ExtractionItemContainer {
  
  @SerializedName("object")
  private MediaObjectDescriptor _object = null;
  @SerializedName("metadata")
  private List<MediaObjectMetadataDescriptor> metadata = null;
  @SerializedName("uri")
  private String uri = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public MediaObjectDescriptor getObject() {
    return _object;
  }
  public void setObject(MediaObjectDescriptor _object) {
    this._object = _object;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<MediaObjectMetadataDescriptor> getMetadata() {
    return metadata;
  }
  public void setMetadata(List<MediaObjectMetadataDescriptor> metadata) {
    this.metadata = metadata;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUri() {
    return uri;
  }
  public void setUri(String uri) {
    this.uri = uri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtractionItemContainer extractionItemContainer = (ExtractionItemContainer) o;
    return (this._object == null ? extractionItemContainer._object == null : this._object.equals(extractionItemContainer._object)) &&
        (this.metadata == null ? extractionItemContainer.metadata == null : this.metadata.equals(extractionItemContainer.metadata)) &&
        (this.uri == null ? extractionItemContainer.uri == null : this.uri.equals(extractionItemContainer.uri));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this._object == null ? 0: this._object.hashCode());
    result = 31 * result + (this.metadata == null ? 0: this.metadata.hashCode());
    result = 31 * result + (this.uri == null ? 0: this.uri.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtractionItemContainer {\n");
    
    sb.append("  _object: ").append(_object).append("\n");
    sb.append("  metadata: ").append(metadata).append("\n");
    sb.append("  uri: ").append(uri).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
