/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import java.util.Map;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class FeaturesAllCategoriesQueryResult {
  
  @SerializedName("queryId")
  private String queryId = null;
  @SerializedName("featureMap")
  private Map<String, List<Object>> featureMap = null;
  @SerializedName("elementID")
  private String elementID = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getQueryId() {
    return queryId;
  }
  public void setQueryId(String queryId) {
    this.queryId = queryId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Map<String, List<Object>> getFeatureMap() {
    return featureMap;
  }
  public void setFeatureMap(Map<String, List<Object>> featureMap) {
    this.featureMap = featureMap;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getElementID() {
    return elementID;
  }
  public void setElementID(String elementID) {
    this.elementID = elementID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeaturesAllCategoriesQueryResult featuresAllCategoriesQueryResult = (FeaturesAllCategoriesQueryResult) o;
    return (this.queryId == null ? featuresAllCategoriesQueryResult.queryId == null : this.queryId.equals(featuresAllCategoriesQueryResult.queryId)) &&
        (this.featureMap == null ? featuresAllCategoriesQueryResult.featureMap == null : this.featureMap.equals(featuresAllCategoriesQueryResult.featureMap)) &&
        (this.elementID == null ? featuresAllCategoriesQueryResult.elementID == null : this.elementID.equals(featuresAllCategoriesQueryResult.elementID));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.queryId == null ? 0: this.queryId.hashCode());
    result = 31 * result + (this.featureMap == null ? 0: this.featureMap.hashCode());
    result = 31 * result + (this.elementID == null ? 0: this.elementID.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeaturesAllCategoriesQueryResult {\n");
    
    sb.append("  queryId: ").append(queryId).append("\n");
    sb.append("  featureMap: ").append(featureMap).append("\n");
    sb.append("  elementID: ").append(elementID).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
