/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.MediaSegmentDescriptor;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class MediaSegmentQueryResult {
  
  @SerializedName("content")
  private List<MediaSegmentDescriptor> content = null;
  @SerializedName("queryId")
  private String queryId = null;
  public enum MessageTypeEnum {
     PING,  Q_SIM,  Q_MLT,  Q_NESEG,  Q_SEG,  M_LOOKUP,  Q_TEMPORAL,  SESSION_START,  QR_START,  QR_END,  QR_ERROR,  QR_OBJECT,  QR_METADATA_O,  QR_METADATA_S,  QR_SEGMENT,  QR_SIMILARITY, 
  };
  @SerializedName("messageType")
  private MessageTypeEnum messageType = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<MediaSegmentDescriptor> getContent() {
    return content;
  }
  public void setContent(List<MediaSegmentDescriptor> content) {
    this.content = content;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getQueryId() {
    return queryId;
  }
  public void setQueryId(String queryId) {
    this.queryId = queryId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public MessageTypeEnum getMessageType() {
    return messageType;
  }
  public void setMessageType(MessageTypeEnum messageType) {
    this.messageType = messageType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MediaSegmentQueryResult mediaSegmentQueryResult = (MediaSegmentQueryResult) o;
    return (this.content == null ? mediaSegmentQueryResult.content == null : this.content.equals(mediaSegmentQueryResult.content)) &&
        (this.queryId == null ? mediaSegmentQueryResult.queryId == null : this.queryId.equals(mediaSegmentQueryResult.queryId)) &&
        (this.messageType == null ? mediaSegmentQueryResult.messageType == null : this.messageType.equals(mediaSegmentQueryResult.messageType));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.content == null ? 0: this.content.hashCode());
    result = 31 * result + (this.queryId == null ? 0: this.queryId.hashCode());
    result = 31 * result + (this.messageType == null ? 0: this.messageType.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MediaSegmentQueryResult {\n");
    
    sb.append("  content: ").append(content).append("\n");
    sb.append("  queryId: ").append(queryId).append("\n");
    sb.append("  messageType: ").append(messageType).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
