/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class MediaSegmentDescriptor {
  
  @SerializedName("segmentId")
  private String segmentId = null;
  @SerializedName("objectId")
  private String objectId = null;
  @SerializedName("start")
  private Integer start = null;
  @SerializedName("end")
  private Integer end = null;
  @SerializedName("startabs")
  private Float startabs = null;
  @SerializedName("endabs")
  private Float endabs = null;
  @SerializedName("count")
  private Integer count = null;
  @SerializedName("sequenceNumber")
  private Integer sequenceNumber = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSegmentId() {
    return segmentId;
  }
  public void setSegmentId(String segmentId) {
    this.segmentId = segmentId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getObjectId() {
    return objectId;
  }
  public void setObjectId(String objectId) {
    this.objectId = objectId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getStart() {
    return start;
  }
  public void setStart(Integer start) {
    this.start = start;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getEnd() {
    return end;
  }
  public void setEnd(Integer end) {
    this.end = end;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Float getStartabs() {
    return startabs;
  }
  public void setStartabs(Float startabs) {
    this.startabs = startabs;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Float getEndabs() {
    return endabs;
  }
  public void setEndabs(Float endabs) {
    this.endabs = endabs;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCount() {
    return count;
  }
  public void setCount(Integer count) {
    this.count = count;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getSequenceNumber() {
    return sequenceNumber;
  }
  public void setSequenceNumber(Integer sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MediaSegmentDescriptor mediaSegmentDescriptor = (MediaSegmentDescriptor) o;
    return (this.segmentId == null ? mediaSegmentDescriptor.segmentId == null : this.segmentId.equals(mediaSegmentDescriptor.segmentId)) &&
        (this.objectId == null ? mediaSegmentDescriptor.objectId == null : this.objectId.equals(mediaSegmentDescriptor.objectId)) &&
        (this.start == null ? mediaSegmentDescriptor.start == null : this.start.equals(mediaSegmentDescriptor.start)) &&
        (this.end == null ? mediaSegmentDescriptor.end == null : this.end.equals(mediaSegmentDescriptor.end)) &&
        (this.startabs == null ? mediaSegmentDescriptor.startabs == null : this.startabs.equals(mediaSegmentDescriptor.startabs)) &&
        (this.endabs == null ? mediaSegmentDescriptor.endabs == null : this.endabs.equals(mediaSegmentDescriptor.endabs)) &&
        (this.count == null ? mediaSegmentDescriptor.count == null : this.count.equals(mediaSegmentDescriptor.count)) &&
        (this.sequenceNumber == null ? mediaSegmentDescriptor.sequenceNumber == null : this.sequenceNumber.equals(mediaSegmentDescriptor.sequenceNumber));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.segmentId == null ? 0: this.segmentId.hashCode());
    result = 31 * result + (this.objectId == null ? 0: this.objectId.hashCode());
    result = 31 * result + (this.start == null ? 0: this.start.hashCode());
    result = 31 * result + (this.end == null ? 0: this.end.hashCode());
    result = 31 * result + (this.startabs == null ? 0: this.startabs.hashCode());
    result = 31 * result + (this.endabs == null ? 0: this.endabs.hashCode());
    result = 31 * result + (this.count == null ? 0: this.count.hashCode());
    result = 31 * result + (this.sequenceNumber == null ? 0: this.sequenceNumber.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MediaSegmentDescriptor {\n");
    
    sb.append("  segmentId: ").append(segmentId).append("\n");
    sb.append("  objectId: ").append(objectId).append("\n");
    sb.append("  start: ").append(start).append("\n");
    sb.append("  end: ").append(end).append("\n");
    sb.append("  startabs: ").append(startabs).append("\n");
    sb.append("  endabs: ").append(endabs).append("\n");
    sb.append("  count: ").append(count).append("\n");
    sb.append("  sequenceNumber: ").append(sequenceNumber).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
