/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class MediaSegmentMetadataDescriptor {
  
  @SerializedName("segmentId")
  private String segmentId = null;
  @SerializedName("domain")
  private String domain = null;
  @SerializedName("key")
  private String key = null;
  @SerializedName("value")
  private String value = null;
  @SerializedName("exists")
  private Boolean exists = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSegmentId() {
    return segmentId;
  }
  public void setSegmentId(String segmentId) {
    this.segmentId = segmentId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDomain() {
    return domain;
  }
  public void setDomain(String domain) {
    this.domain = domain;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getKey() {
    return key;
  }
  public void setKey(String key) {
    this.key = key;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getValue() {
    return value;
  }
  public void setValue(String value) {
    this.value = value;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getExists() {
    return exists;
  }
  public void setExists(Boolean exists) {
    this.exists = exists;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MediaSegmentMetadataDescriptor mediaSegmentMetadataDescriptor = (MediaSegmentMetadataDescriptor) o;
    return (this.segmentId == null ? mediaSegmentMetadataDescriptor.segmentId == null : this.segmentId.equals(mediaSegmentMetadataDescriptor.segmentId)) &&
        (this.domain == null ? mediaSegmentMetadataDescriptor.domain == null : this.domain.equals(mediaSegmentMetadataDescriptor.domain)) &&
        (this.key == null ? mediaSegmentMetadataDescriptor.key == null : this.key.equals(mediaSegmentMetadataDescriptor.key)) &&
        (this.value == null ? mediaSegmentMetadataDescriptor.value == null : this.value.equals(mediaSegmentMetadataDescriptor.value)) &&
        (this.exists == null ? mediaSegmentMetadataDescriptor.exists == null : this.exists.equals(mediaSegmentMetadataDescriptor.exists));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.segmentId == null ? 0: this.segmentId.hashCode());
    result = 31 * result + (this.domain == null ? 0: this.domain.hashCode());
    result = 31 * result + (this.key == null ? 0: this.key.hashCode());
    result = 31 * result + (this.value == null ? 0: this.value.hashCode());
    result = 31 * result + (this.exists == null ? 0: this.exists.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MediaSegmentMetadataDescriptor {\n");
    
    sb.append("  segmentId: ").append(segmentId).append("\n");
    sb.append("  domain: ").append(domain).append("\n");
    sb.append("  key: ").append(key).append("\n");
    sb.append("  value: ").append(value).append("\n");
    sb.append("  exists: ").append(exists).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
