/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.QueryTerm;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class QueryComponent {
  
  @SerializedName("terms")
  private List<QueryTerm> terms = null;
  @SerializedName("containerId")
  private Integer containerId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<QueryTerm> getTerms() {
    return terms;
  }
  public void setTerms(List<QueryTerm> terms) {
    this.terms = terms;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getContainerId() {
    return containerId;
  }
  public void setContainerId(Integer containerId) {
    this.containerId = containerId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryComponent queryComponent = (QueryComponent) o;
    return (this.terms == null ? queryComponent.terms == null : this.terms.equals(queryComponent.terms)) &&
        (this.containerId == null ? queryComponent.containerId == null : this.containerId.equals(queryComponent.containerId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.terms == null ? 0: this.terms.hashCode());
    result = 31 * result + (this.containerId == null ? 0: this.containerId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryComponent {\n");
    
    sb.append("  terms: ").append(terms).append("\n");
    sb.append("  containerId: ").append(containerId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
