/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import java.util.Map;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SelectResult {
  
  @SerializedName("columns")
  private List<Map<String, String>> columns = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Map<String, String>> getColumns() {
    return columns;
  }
  public void setColumns(List<Map<String, String>> columns) {
    this.columns = columns;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SelectResult selectResult = (SelectResult) o;
    return (this.columns == null ? selectResult.columns == null : this.columns.equals(selectResult.columns));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.columns == null ? 0: this.columns.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SelectResult {\n");
    
    sb.append("  columns: ").append(columns).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
