/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SelectSpecification {
  
  @SerializedName("table")
  private String table = null;
  @SerializedName("columns")
  private List<String> columns = null;
  @SerializedName("limit")
  private Integer limit = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTable() {
    return table;
  }
  public void setTable(String table) {
    this.table = table;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getColumns() {
    return columns;
  }
  public void setColumns(List<String> columns) {
    this.columns = columns;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getLimit() {
    return limit;
  }
  public void setLimit(Integer limit) {
    this.limit = limit;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SelectSpecification selectSpecification = (SelectSpecification) o;
    return (this.table == null ? selectSpecification.table == null : this.table.equals(selectSpecification.table)) &&
        (this.columns == null ? selectSpecification.columns == null : this.columns.equals(selectSpecification.columns)) &&
        (this.limit == null ? selectSpecification.limit == null : this.limit.equals(selectSpecification.limit));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.table == null ? 0: this.table.hashCode());
    result = 31 * result + (this.columns == null ? 0: this.columns.hashCode());
    result = 31 * result + (this.limit == null ? 0: this.limit.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SelectSpecification {\n");
    
    sb.append("  table: ").append(table).append("\n");
    sb.append("  columns: ").append(columns).append("\n");
    sb.append("  limit: ").append(limit).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
