/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SessionState {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("validUntil")
  private Long validUntil = null;
  public enum TypeEnum {
     UNAUTHENTICATED,  USER,  ADMIN, 
  };
  @SerializedName("type")
  private TypeEnum type = null;
  @SerializedName("sessionId")
  private String sessionId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getValidUntil() {
    return validUntil;
  }
  public void setValidUntil(Long validUntil) {
    this.validUntil = validUntil;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public TypeEnum getType() {
    return type;
  }
  public void setType(TypeEnum type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSessionId() {
    return sessionId;
  }
  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionState sessionState = (SessionState) o;
    return (this.id == null ? sessionState.id == null : this.id.equals(sessionState.id)) &&
        (this.validUntil == null ? sessionState.validUntil == null : this.validUntil.equals(sessionState.validUntil)) &&
        (this.type == null ? sessionState.type == null : this.type.equals(sessionState.type)) &&
        (this.sessionId == null ? sessionState.sessionId == null : this.sessionId.equals(sessionState.sessionId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.validUntil == null ? 0: this.validUntil.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.sessionId == null ? 0: this.sessionId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionState {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  validUntil: ").append(validUntil).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  sessionId: ").append(sessionId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
