/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.SimilarityQueryResult;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SimilarityQueryResultBatch {
  
  @SerializedName("categories")
  private List<String> categories = null;
  @SerializedName("results")
  private List<SimilarityQueryResult> results = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getCategories() {
    return categories;
  }
  public void setCategories(List<String> categories) {
    this.categories = categories;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<SimilarityQueryResult> getResults() {
    return results;
  }
  public void setResults(List<SimilarityQueryResult> results) {
    this.results = results;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimilarityQueryResultBatch similarityQueryResultBatch = (SimilarityQueryResultBatch) o;
    return (this.categories == null ? similarityQueryResultBatch.categories == null : this.categories.equals(similarityQueryResultBatch.categories)) &&
        (this.results == null ? similarityQueryResultBatch.results == null : this.results.equals(similarityQueryResultBatch.results));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.categories == null ? 0: this.categories.hashCode());
    result = 31 * result + (this.results == null ? 0: this.results.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimilarityQueryResultBatch {\n");
    
    sb.append("  categories: ").append(categories).append("\n");
    sb.append("  results: ").append(results).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
