/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.QueryComponent;
import org.openapitools.client.model.QueryConfig;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SimilarityQuery {
  
  @SerializedName("containers")
  private List<QueryComponent> containers = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<QueryComponent> getContainers() {
    return containers;
  }
  public void setContainers(List<QueryComponent> containers) {
    this.containers = containers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimilarityQuery similarityQuery = (SimilarityQuery) o;
    return (this.containers == null ? similarityQuery.containers == null : this.containers.equals(similarityQuery.containers));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.containers == null ? 0: this.containers.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimilarityQuery {\n");
    
    sb.append("  containers: ").append(containers).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
