/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.StringDoublePair;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SimilarityQueryResult {
  
  @SerializedName("content")
  private List<StringDoublePair> content = null;
  @SerializedName("queryId")
  private String queryId = null;
  @SerializedName("category")
  private String category = null;
  @SerializedName("containerId")
  private Integer containerId = null;
  public enum MessageTypeEnum {
     PING,  Q_SIM,  Q_MLT,  Q_NESEG,  Q_SEG,  M_LOOKUP,  Q_TEMPORAL,  SESSION_START,  QR_START,  QR_END,  QR_ERROR,  QR_OBJECT,  QR_METADATA_O,  QR_METADATA_S,  QR_SEGMENT,  QR_SIMILARITY, 
  };
  @SerializedName("messageType")
  private MessageTypeEnum messageType = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<StringDoublePair> getContent() {
    return content;
  }
  public void setContent(List<StringDoublePair> content) {
    this.content = content;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getQueryId() {
    return queryId;
  }
  public void setQueryId(String queryId) {
    this.queryId = queryId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCategory() {
    return category;
  }
  public void setCategory(String category) {
    this.category = category;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getContainerId() {
    return containerId;
  }
  public void setContainerId(Integer containerId) {
    this.containerId = containerId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public MessageTypeEnum getMessageType() {
    return messageType;
  }
  public void setMessageType(MessageTypeEnum messageType) {
    this.messageType = messageType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimilarityQueryResult similarityQueryResult = (SimilarityQueryResult) o;
    return (this.content == null ? similarityQueryResult.content == null : this.content.equals(similarityQueryResult.content)) &&
        (this.queryId == null ? similarityQueryResult.queryId == null : this.queryId.equals(similarityQueryResult.queryId)) &&
        (this.category == null ? similarityQueryResult.category == null : this.category.equals(similarityQueryResult.category)) &&
        (this.containerId == null ? similarityQueryResult.containerId == null : this.containerId.equals(similarityQueryResult.containerId)) &&
        (this.messageType == null ? similarityQueryResult.messageType == null : this.messageType.equals(similarityQueryResult.messageType));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.content == null ? 0: this.content.hashCode());
    result = 31 * result + (this.queryId == null ? 0: this.queryId.hashCode());
    result = 31 * result + (this.category == null ? 0: this.category.hashCode());
    result = 31 * result + (this.containerId == null ? 0: this.containerId.hashCode());
    result = 31 * result + (this.messageType == null ? 0: this.messageType.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimilarityQueryResult {\n");
    
    sb.append("  content: ").append(content).append("\n");
    sb.append("  queryId: ").append(queryId).append("\n");
    sb.append("  category: ").append(category).append("\n");
    sb.append("  containerId: ").append(containerId).append("\n");
    sb.append("  messageType: ").append(messageType).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
