/**
 * Cineast RESTful API
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.QueryComponent;
import org.openapitools.client.model.QueryConfig;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SimilarityQuery {
  
  @SerializedName("containers")
  private List<QueryComponent> containers = null;
  @SerializedName("config")
  private QueryConfig config = null;
  @SerializedName("components")
  private List<QueryComponent> components = null;
  public enum MessageTypeEnum {
     PING,  Q_SIM,  Q_MLT,  Q_NESEG,  Q_SEG,  M_LOOKUP,  Q_TEMPORAL,  SESSION_START,  QR_START,  QR_END,  QR_ERROR,  QR_OBJECT,  QR_METADATA_O,  QR_METADATA_S,  QR_SEGMENT,  QR_SIMILARITY, 
  };
  @SerializedName("messageType")
  private MessageTypeEnum messageType = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<QueryComponent> getContainers() {
    return containers;
  }
  public void setContainers(List<QueryComponent> containers) {
    this.containers = containers;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public QueryConfig getConfig() {
    return config;
  }
  public void setConfig(QueryConfig config) {
    this.config = config;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<QueryComponent> getComponents() {
    return components;
  }
  public void setComponents(List<QueryComponent> components) {
    this.components = components;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public MessageTypeEnum getMessageType() {
    return messageType;
  }
  public void setMessageType(MessageTypeEnum messageType) {
    this.messageType = messageType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimilarityQuery similarityQuery = (SimilarityQuery) o;
    return (this.containers == null ? similarityQuery.containers == null : this.containers.equals(similarityQuery.containers)) &&
        (this.config == null ? similarityQuery.config == null : this.config.equals(similarityQuery.config)) &&
        (this.components == null ? similarityQuery.components == null : this.components.equals(similarityQuery.components)) &&
        (this.messageType == null ? similarityQuery.messageType == null : this.messageType.equals(similarityQuery.messageType));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.containers == null ? 0: this.containers.hashCode());
    result = 31 * result + (this.config == null ? 0: this.config.hashCode());
    result = 31 * result + (this.components == null ? 0: this.components.hashCode());
    result = 31 * result + (this.messageType == null ? 0: this.messageType.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimilarityQuery {\n");
    
    sb.append("  containers: ").append(containers).append("\n");
    sb.append("  config: ").append(config).append("\n");
    sb.append("  components: ").append(components).append("\n");
    sb.append("  messageType: ").append(messageType).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
